console.log('test.js loaded')
console.log('ci commit')
console.log('build infrastructureManagement')
console.log('build infrastructureManagement 3')
console.log('build infrastructureManagement 4')
console.log('docs')