console.log('initial commit')
console.log('bogus commit')
console.log('test commit')
console.log('test commit')
console.log('test commit')
console.log('test commit')
console.log('test commit')
console.log('fix commit')
console.log('another bogus commit')
console.log('perf')
console.log('style')
console.log('revert')
console.log('fix somehting')